Bookstore.UI/Areas/Admin/Controllers/BuyerController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bookstore.UI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace Bookstore.UI.Areas.Admin.Controllers
{
  [Authorize(Roles = RoleList.Admin)]
  public class BuyerController : Controller
  {
    private ApplicationDbContext _dbContext;

    private ApplicationUserManager _userManager;

    public BuyerController()
    {
    }

    public BuyerController(ApplicationUserManager userManager, ApplicationDbContext dbContext)
    {
      UserManager = userManager;
      DbContext = dbContext;
    }

    public ApplicationUserManager UserManager
    {
      get =>
        _userManager ?? HttpContext.GetOwinContext()
          .GetUserManager<ApplicationUserManager>();
      private set => _userManager = value;
    }

    public ApplicationDbContext DbContext
    {
      get => _dbContext ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
      private set => _dbContext = value;
    }

    public async Task<ActionResult> Index()
    {
      var query = await UserManager.Users.ToArrayAsync();

      return View(query.Where(w => UserManager.IsInRole(w.Id, RoleList.Buyer)));
    }

    public async Task<ActionResult> Delete(string id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var user = await UserManager.FindByIdAsync(id);
      if (user == null)
        return HttpNotFound();

      user.IsDeleted = true;

      await UserManager.UpdateAsync(user);

      //var books = DbContext.Books.Where(a => a.BuyerId == id);

      //foreach (var item in books)
      //{
      //  item.IsDeleted = true;

      //  DbContext.Entry(item).State = EntityState.Modified;
      //}

      //await DbContext.SaveChangesAsync();

      return RedirectToAction("Index");
    }
     
  }
}

Bookstore.UI/Controllers/BookController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bookstore.UI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;

namespace Bookstore.UI.Controllers
{
  public class BookController : Controller
  {
    private ApplicationDbContext _dbContext;

    public BookController()
    {
    }

    public BookController(ApplicationDbContext dbContext)
    {
      _dbContext = dbContext;
    }

    public ApplicationDbContext DbContext
    {
      get => _dbContext ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
      private set => _dbContext = value;
    }

    public ActionResult Index(string search, int? minPrice, int? maxPrice, int page = 1)
    {
      var size = 10;
      var query = DbContext.Books.Where(a => a.BuyerId == null && a.Offered == null);

      if (!string.IsNullOrWhiteSpace(search)) query = query.Where(a => a.Name.Contains(search));

      if (minPrice.HasValue && !maxPrice.HasValue) query = query.Where(a => a.Price >= minPrice.Value);

      if (!minPrice.HasValue && maxPrice.HasValue) query = query.Where(a => a.Price <= maxPrice.Value);

      if (minPrice.HasValue && maxPrice.HasValue)
        query = query.Where(a => a.Price >= minPrice.Value && a.Price <= maxPrice.Value);

      ViewBag.Search = search;
      ViewBag.MinPrice = minPrice;
      ViewBag.MaxPrice = maxPrice;

      return View(query.OrderByDescending(a => a.Id).ToPagedList(page, size));
    }

    public ActionResult Archive(string search, int? minPrice, int? maxPrice, int page = 1)
    {
      var size = 10;
      var query = DbContext.Books.Where(a => a.BuyerId != null && a.Offered == true);

      if (!string.IsNullOrWhiteSpace(search)) query = query.Where(a => a.Name.Contains(search));

      if (minPrice.HasValue && !maxPrice.HasValue) query = query.Where(a => a.Price >= minPrice.Value);

      if (!minPrice.HasValue && maxPrice.HasValue) query = query.Where(a => a.Price <= maxPrice.Value);

      if (minPrice.HasValue && maxPrice.HasValue)
        query = query.Where(a => a.Price >= minPrice.Value && a.Price <= maxPrice.Value);

      ViewBag.Search = search;
      ViewBag.MinPrice = minPrice;
      ViewBag.MaxPrice = maxPrice;

      return View(query.OrderByDescending(a => a.Id).ToPagedList(page, size));
    }

    [Authorize(Roles = RoleList.Buyer)]
    public ActionResult Offer(int page = 1)
    {
      var size = 10;
      var userId = User.Identity.GetUserId();
      var query = DbContext.Books.Where(a => a.BuyerId == userId).Include(a => a.Seller);

      return View(query.OrderByDescending(b => b.Id).ToPagedList(page, size));
    }

    public ActionResult Deal(int page = 1)
    {
      var size = 10;
      var query = DbContext.Books.Where(a => a.BuyerId != null || a.Offered != null).Include(a => a.Buyer);

      return View(query.OrderByDescending(b => b.Id).ToPagedList(page, size));
    }

    public async Task<ActionResult> Details(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var model = await DbContext.Books.Where(t => t.Id == id).Include(a => a.Buyer).Include(a => a.Seller).FirstOrDefaultAsync();

      if (model == null)
        return HttpNotFound();

      return View(model);
    }

    [Authorize(Roles = RoleList.Seller)]
    public ActionResult Add()
    {
      return View();
    }

    [Authorize(Roles = RoleList.Seller)]
    [HttpPost]
    public async Task<ActionResult> Add(Book model)
    {
      if (ModelState.IsValid)
      {
        model.SellerId = User.Identity.GetUserId();
        model.CoverImagePath = "~/Images/Covers/DefaultBookCover.jpg";
        model.CreatedDate = DateTime.Now;
        model.ModifiedDate = DateTime.Now;

        if (Request.Files != null && Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
        {
          var fileName = Path.GetFileName(Request.Files[0].FileName);
          var filePathOfWebsite = "~/Images/Covers/" + fileName;
          model.CoverImagePath = filePathOfWebsite;
          Request.Files[0].SaveAs(Server.MapPath(filePathOfWebsite));
        }

        DbContext.Books.Add(model);

        await DbContext.SaveChangesAsync();

        return RedirectToAction("Index");
      }

      return View(model);
    }

    [Authorize(Roles = RoleList.Buyer)]
    [HttpPost]
    public async Task<ActionResult> Order(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var model = await DbContext.Books.FindAsync(id);

      if (model == null)
        return HttpNotFound();

      if (model.Offered == null && model.BuyerId == null)
      {
        model.BuyerId = User.Identity.GetUserId();

        DbContext.Entry(model).State = EntityState.Modified;

        await DbContext.SaveChangesAsync();

        TempData["message"] = "Order submission successful!";
      }

      return RedirectToAction("Details", new { id });
    }

    [Authorize(Roles = RoleList.Seller)]
    [HttpPost]
    public async Task<ActionResult> Accept(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var model = await DbContext.Books.FindAsync(id);

      if (model == null)
        return HttpNotFound();

      if (model.Offered == null && model.BuyerId != null)
      {
        model.Offered = true;
        model.OfferDate = DateTime.Now;

        DbContext.Entry(model).State = EntityState.Modified;

        await DbContext.SaveChangesAsync();

        TempData["message"] = "Order accepted.";
      }

      return RedirectToAction("Details", new { id });
    }

    [Authorize(Roles = RoleList.Seller)]
    [HttpPost]
    public async Task<ActionResult> Available(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var model = await DbContext.Books.FindAsync(id);

      if (model == null)
        return HttpNotFound();

      if (model.Offered == false && model.BuyerId != null)
      {
        model.Offered = null;
        model.OfferDate = null;
        model.BuyerId = null;

        DbContext.Entry(model).State = EntityState.Modified;

        await DbContext.SaveChangesAsync();

        TempData["message"] = "Book is available for buyers.";
      }

      return RedirectToAction("Details", new { id });
    }

    [Authorize(Roles = RoleList.Seller)]
    [HttpPost]
    public async Task<ActionResult> Reject(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var model = await DbContext.Books.FindAsync(id);

      if (model == null)
        return HttpNotFound();

      if (model.Offered == null && model.BuyerId != null)
      {
        model.Offered = false;

        DbContext.Entry(model).State = EntityState.Modified;

        await DbContext.SaveChangesAsync();

        TempData["message"] = "Order rejected!";
      }

      return RedirectToAction("Details", new { id });
    }

    [Authorize(Roles = RoleList.Seller)]
    public async Task<ActionResult> Delete(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var model = await DbContext.Books.FindAsync(id);

      if (model == null)
        return HttpNotFound();

      model.IsDeleted = true;

      DbContext.Entry(model).State = EntityState.Modified;

      await DbContext.SaveChangesAsync();

      return RedirectToAction("Index");
    }

    [Authorize(Roles = RoleList.Seller)]
    public async Task<ActionResult> Edit(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var model = await DbContext.Books.FindAsync(id);

      if (model == null)
        return HttpNotFound();

      return View(model);
    }

    [Authorize(Roles = RoleList.Seller)]
    [HttpPost]
    public async Task<ActionResult> Edit(int? id, Book model)
    {
      if (!ModelState.IsValid)
        return View(model);

      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      var ent = await DbContext.Books.FindAsync(id);

      if (ent == null)
        return HttpNotFound();

      ent.SellerId = User.Identity.GetUserId();
      ent.Condition = model.Condition;
      ent.PublishYear = model.PublishYear;
      ent.Description = model.Description;
      ent.ISBN = model.ISBN;
      ent.Price = model.Price;
      ent.Name = model.Name;
      ent.ModifiedDate = DateTime.Now;

      if (Request.Files != null && Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
      {
        var fileName = Path.GetFileName(Request.Files[0].FileName);
        var filePathOfWebsite = "~/Images/Covers/" + fileName;
        ent.CoverImagePath = filePathOfWebsite;
        Request.Files[0].SaveAs(Server.MapPath(filePathOfWebsite));
      }

      DbContext.Entry(ent).State = EntityState.Modified;

      await DbContext.SaveChangesAsync();

      return RedirectToAction("Index");
    }
  }
}

Bookstore.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - Welcome to MVC Bookstore</title>
  <link rel="shortcut icon" type="image/x-icon" href="~/Images/favicon.ico" />
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
  <link href="~/Content/Site.css" rel="stylesheet" />
  @RenderSection("styles", false)
</head>
<body>
  <div class="navbar navbar-inverse custom-nav-fix navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="@Url.Action("Index", "Book", new {  area="" }, null)" class="navbar-brand">
          <img src="~/Images/Layout/logo.png" class="img-responsive center-block" width="100" />
        </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
           
          <li>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-book"></span>  Books <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="@Url.Action("Index", "Book", new { maxPrice = 20 ,area=""}, null)"> < 20$</a></li>
              <li><a href="@Url.Action("Index", "Book", new { minPrice = 20, maxPrice = 50 ,area=""}, null)">  20$-50$</a></li>
              <li><a href="@Url.Action("Index", "Book", new { minPrice = 50, area=""}, null)">  50$ < </a></li>
              <li role="separator" class="divider"></li>
              <li>
                <a href="@Url.Action("Index", "Book", new { area=""})"> All </a>
              </li>
            </ul>
          </li> 

          <li>
            <a href="@Url.Action("Archive","Book", new { area=""})"><span class="glyphicon glyphicon-briefcase"></span> Archive</a>
          </li>

          @if (User.IsInRole(RoleList.Admin))
          {
            <li>
              <a href="@Url.Action("Index", "Buyer", new { area="Admin"})"><span class="glyphicon glyphicon-user"></span> Buyers </a>
            </li>
          }

          @if (User.IsInRole(RoleList.Buyer))
          {
            <li>
              <a href="@Url.Action("Offer","Book", new { area=""})"><span class="glyphicon glyphicon-shopping-cart"></span> Offers </a>
            </li>
          }

          @if (User.IsInRole(RoleList.Seller))
          {
            <li>
              <a href="@Url.Action("Deal","Book", new { area=""})"><span class="glyphicon glyphicon-shopping-cart"></span> Deals</a>
            </li>
          }

        </ul>
        @Html.Partial("_LoginPartial")
      </div>
    </div>
  </div>
  <br />
  <br />
  <div class="container body-content">

    <div class="page-header">
      <h2>@ViewBag.Title</h2>
    </div>

    <div class="row">
      @RenderBody()
    </div>
    <hr />
    <footer>
      <p>&copy; @DateTime.Now.Year - Online Book Shop</p>
    </footer>
  </div>

  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  <script src="~/Scripts/nav.js"></script>
  @RenderSection("scripts", required: false)
</body>
</html>